### ISSUE TITLE
Another hidden sber infrastructure

### ISSUE THREAD

**Issue by greenycat** [eitzenbe/StandWithUkraine#1]
Add please:
https://scr.online.sberbank.ru/api/fl/idgib-w-3ds
https://3dsec.sberbank.ru/mportal3/auth/login
https://acs1.sbrf.ru
https://acs2.sbrf.ru
https://acs3.sbrf.ru
https://acs4.sbrf.ru
https://acs5.sbrf.ru
https://acs6.sbrf.ru
https://acs7.sbrf.ru
https://acs8.sbrf.ru

**Comment by eitzenbe** [comment]
updated in v1.7 which is out by now ;)
